apiVersion: v1
data:
  password: SOMEBASE64PASS
  username: SOMEBASE64USER
kind: Secret
metadata:
  annotations:
    jenkins.io/name: github-jira-bot-jira-secret
  labels:
    jenkins.io/created-by: You
    jenkins.io/credentials-type: usernamePassword
  name: github-jira-bot-jira-secret
type: Opaque
---
apiVersion: v1
data:
  password: SOMEBASE64PASS
  username: SOMEBASE64USER
kind: Secret
metadata:
  annotations:
    jenkins.io/name: github-jira-bot-gh-secret
  labels:
    jenkins.io/created-by: You
    jenkins.io/credentials-type: usernamePassword
  name: github-jira-bot-gh-secret
type: Opaque
---
apiVersion: v1
data:
  password: SOMEBASE64URL
  username: SOMEBASE64URL
kind: Secret
metadata:
  annotations:
    jenkins.io/name: github-jira-bot-urls
  labels:
    jenkins.io/created-by: You
    jenkins.io/credentials-type: usernamePassword
  name: github-jira-bot-urls
type: Opaque

